---
metadata:
  pagetitle: "econdataverse"
  description-meta: "An ecosystem of packages to work with economic data in R and Python."
format: 
  html:
    include-in-header: 
      - assets/html/header-particles.html
    include-after-body: 
      - assets/html/bottom-particles.html
    css:
      - assets/css/styles-index.css
---

::: {#particles-js}
::: {#particles-text}
## econdataverse

An universe of open-source packages to seamlessly work with economic data in R and Python

:::
:::

::: {#index-text}
## Goal

 The landscape of economic data tools is **fragmented**, with packages differing widely in design, syntax, and usability, which can be a significant barrier for analysts and researchers who rely on multi-source data. These **inconsistencies** make it challenging to switch between sources and often require users to invest time in learning multiple interfaces or reformatting data, diverting attention from analysis and insight generation. 

 The econdataverse addresses these challenges by establishing a **standardized**, **cross-language** framework, enabling users to access, explore, and analyze economic data seamlessly. Through consistent function names, tidy data outputs, and multi-language support, the econdataverse exists to eliminate these common pain points, empowering users to **focus on research** and **analysis** rather than data wrangling.

## Design Principles

### Consistent Interface 

Every package within the econdataverse follows a standardized interface with **predictable patterns**. For instance, functions for data retrieval are named consistently: `*_get` functions retrieve data from a specific source, `*_list` functions enumerate available resources.

### Coding Style

For R packages, the econdataverse adopts the tidyverse coding style and enforces it through `{lintr}`. For Python, we use the same naming conventions, but respect style conventions layout out in PEP 8. These styles enhance the **readability** of code and align with the practices of users familiar with the corresponding language. 

### Tidy Data Outputs

All packages return data in a tidy format, with each variable as a column, each observation as a row, and each data type as a table. Defaulting to tidy data ensures **compatibility** with popular data manipulation and visualization libraries in both R and Python. 

### Comprehensive Unit Testing

Each package is thoroughly tested through extensive unit tests, which ensure consistent functionality, protect against regressions, and help users **trust** that the packages will work as expected across different environments.

### Open-Source Licensing

All packages are released under the MIT License, which permits wide usage and modification. The MIT License promotes **transparency**, allowing users to freely adapt the tools for their specific needs while contributing improvements to the community.

### Multi-Language Compatibility

Wherever feasible, econdataverse interfaces are designed to work across languages. Consistency across languages enables analysts and researchers to incorporate these tools into various projects, regardless of language preference, and fosters a **collaborative**, multi-lingual community.

## Roadmap

There will be a table here

## Sponsors

Add logos of TIs

## Contribute

Add contact form

:::



